apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: vectro-cluster
  region: us-east-1
  version: "1.29"

iam:
  withOIDC: true   # required for IRSA (IAM Roles for Service Accounts)

managedNodeGroups:
  - name: vectro-nodes
    instanceType: t3.medium
    minSize: 2
    maxSize: 4
    desiredCapacity: 2
    privateNetworking: true
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy
  - name: aws-ebs-csi-driver
