apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-sa
  namespace: tekton-builds
  annotations:
    # IRSA: replace <TEKTON_ECR_ROLE_ARN> after creating the IAM role in Step 2
    # Run: aws iam list-roles --query "Roles[?RoleName=='tekton-ecr-push-role'].Arn" --output text
    eks.amazonaws.com/role-arn: arn:aws:iam::208073622683:role/tekton-ecr-push-role
