apiVersion: v1
kind: ConfigMap
metadata:
  name: vectro-config
  namespace: vectro
data:
  # ── Server ────────────────────────────────────────────────────────────────
  SERVER_PORT: "8080"

  # ── AWS Region ────────────────────────────────────────────────────────────
  AWS_REGION: "us-east-1"

  # ── Cognito User Pool ─────────────────────────────────────────────────────
  COGNITO_USER_POOL_ID: "us-east-1_smywMCPFv"
  COGNITO_CLIENT_ID: "6uu3lhj6otpept6t35httg4sct"
  COGNITO_ISSUER_URI: "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_smywMCPFv"
  COGNITO_JWKS_URI: "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_smywMCPFv/.well-known/jwks.json"

  # ── Logging ───────────────────────────────────────────────────────────────
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_APP: "DEBUG"
